//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPalautettavaSKe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tunnit
    {
        public int TuntiId { get; set; }
        public int ProjektiId { get; set; }
        public int HenkiloId { get; set; }
        public System.DateTime Päivämäärä { get; set; }
        public decimal Tunnit1 { get; set; }
    }
}
